services:
  postgres:
    image: postgres:18-alpine
    command: -p ${POSTGRES_PORT:-5432}
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER']
      interval: 5s
      timeout: 5s
      retries: 5

  internship:
    build: .
    ports:
      - ${PORT:-8000}:${PORT:-8000}
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_DATABASE=${POSTGRES_DATABASE:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - PORT=${PORT:-8000}
      - JWT_TOKEN=${JWT_TOKEN:-secret}
      - INTERNAL_TOKEN=${INTERNAL_TOKEN:-secret}

volumes:
  postgres_data:
