basePath: /api/v1
definitions:
  Internship:
    properties:
      description:
        type: string
      goals:
        items:
          type: string
        type: array
      id:
        type: integer
      label:
        type: string
      skills:
        items:
          type: string
        type: array
      title:
        type: string
    type: object
info:
  contact: {}
  title: Internship API
paths:
  /internships:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Internship'
            type: array
      summary: Получить все стажировки
      tags:
      - internship
swagger: "2.0"
