components:
  schemas:
    APIError:
      properties:
        details:
          additionalProperties: {}
          type: object
        error:
          type: string
      type: object
    InternshipCreateDto:
      properties:
        description:
          type: string
        goals:
          items:
            type: string
          type: array
          uniqueItems: false
        label:
          type: string
        skills:
          items:
            type: string
          type: array
          uniqueItems: false
        title:
          type: string
      type: object
    InternshipDto:
      properties:
        description:
          type: string
        goals:
          items:
            type: string
          type: array
          uniqueItems: false
        id:
          type: integer
        label:
          type: string
        skills:
          items:
            type: string
          type: array
          uniqueItems: false
        title:
          type: string
      type: object
externalDocs:
  description: ""
  url: ""
info:
  title: Internships API
  version: ""
openapi: 3.1.0
paths:
  /admin/internships:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InternshipCreateDto'
              description: Стажировка
              summary: internship
        description: Стажировка
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternshipDto'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: Bad Request
      summary: Создать стажировку
      tags:
      - internship
  /internships:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/InternshipDto'
                type: array
          description: OK
      summary: Получить все стажировки
      tags:
      - internship
  /internships/{id}:
    get:
      parameters:
      - description: ID стажировки
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternshipDto'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: Bad Request
      summary: Получить стажировку по ID
      tags:
      - internship
servers:
- url: /api/v1
